ERROR: Only reserved 0 of 1 requested devices. You probably need to clear stale locks in arcus-6:/tmp/gpuLock/.
Running from arcus-2.ics.uci.edu
2019-05-13 13:32:18.420519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: GeForce GTX TITAN major: 3 minor: 5 memoryClockRate(GHz): 0.8755
pciBusID: 0000:02:00.0
totalMemory: 5.94GiB freeMemory: 5.87GiB
2019-05-13 13:32:18.420781: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-05-13 13:32:18.844826: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-13 13:32:18.844892: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-05-13 13:32:18.844906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-05-13 13:32:18.845198: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5662 MB memory) -> physical GPU (device: 0, name: GeForce GTX TITAN, pci bus id: 0000:02:00.0, compute capability: 3.5)
{'alpha': 0.4438302659087249, 'dropout': 0.3596089142078868, 'lr': 0.0008177854873906206, 'leaky_relu': 0.43770026777703924, 'batch_norm': 1, 'loss_type': 'mse', 'num_layers': 7, 'layer_0': 86, 'layer_1': 327, 'layer_2': 119, 'layer_3': 345, 'layer_4': 240, 'layer_5': 334, 'layer_6': 245, 'layer_7': 441, 'max_concurrent': 4, 'P': 'arcus_gpu.p', 'q': 'arcus.q', 'l': "hostname='(arcus-1|arcus-2|arcus-3|arcus-4|arcus-5|arcus-6|arcus-7|arcus-8|arcus-9|arcus-10)'", 'env': '/home/jott1/Projects/SHERPA_EX/.profile', 'data': 'fluxbypass_aqua', 'run_type': 'hyper_param_opt_conservation', 'batch_size': 2048, 'data_dir': '/baldig/chemistry/earth_system_science/', 'max_dense_layers': 8, 'epochs': 25, 'patience': 10, 'conservation': 1}
Epoch 1/25
 - 4164s - loss: 468.6300 - mean_squared_error: 468.6300 - val_loss: 377.1082 - val_mean_squared_error: 377.1082
Epoch 2/25
 - 4024s - loss: 376.1277 - mean_squared_error: 376.1277 - val_loss: 387.9922 - val_mean_squared_error: 387.9922
Epoch 3/25
 - 4137s - loss: 370.1468 - mean_squared_error: 370.1468 - val_loss: 371.8930 - val_mean_squared_error: 371.8930
Epoch 4/25
 - 3933s - loss: 366.6996 - mean_squared_error: 366.6996 - val_loss: 368.4159 - val_mean_squared_error: 368.4159
Epoch 5/25
 - 4336s - loss: 364.6631 - mean_squared_error: 364.6631 - val_loss: 396.4655 - val_mean_squared_error: 396.4655
Epoch 6/25
 - 4666s - loss: 363.1794 - mean_squared_error: 363.1794 - val_loss: 382.1293 - val_mean_squared_error: 382.1293
Epoch 7/25
 - 4721s - loss: 361.9736 - mean_squared_error: 361.9736 - val_loss: 380.6695 - val_mean_squared_error: 380.6695
Epoch 8/25
 - 4510s - loss: 361.1878 - mean_squared_error: 361.1878 - val_loss: 392.7230 - val_mean_squared_error: 392.7230
Epoch 9/25
 - 4379s - loss: 360.4808 - mean_squared_error: 360.4808 - val_loss: 390.7004 - val_mean_squared_error: 390.7004
Epoch 10/25
 - 5201s - loss: 359.7965 - mean_squared_error: 359.7965 - val_loss: 392.5511 - val_mean_squared_error: 392.5511
Epoch 11/25
 - 4925s - loss: 359.3733 - mean_squared_error: 359.3733 - val_loss: 404.4072 - val_mean_squared_error: 404.4072
Epoch 12/25
 - 4205s - loss: 358.9317 - mean_squared_error: 358.9317 - val_loss: 391.9300 - val_mean_squared_error: 391.9300
Epoch 13/25
 - 4586s - loss: 358.5706 - mean_squared_error: 358.5706 - val_loss: 397.1327 - val_mean_squared_error: 397.1327
Epoch 14/25
 - 4261s - loss: 358.1817 - mean_squared_error: 358.1817 - val_loss: 406.4492 - val_mean_squared_error: 406.4492
/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    net.train(train_gen, valid_gen, trial=trial, client=client)
  File "/home/jott1/Projects/CBRAIN-CAM/notebooks/tbeucler_devlog/hp_opt_conservation/model.py", line 140, in train
    json_file.write(history.history)
TypeError: write() argument must be str, not dict
