ERROR: Only reserved 0 of 1 requested devices. You probably need to clear stale locks in arcus-4.ics.uci.edu:/tmp/gpuLock/.
Running from arcus-8
2019-05-18 04:41:05.290802: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-18 04:41:05.965737: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2019-05-18 04:41:05.965810: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: arcus-8
2019-05-18 04:41:05.965824: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: arcus-8
2019-05-18 04:41:05.965899: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:194] libcuda reported version is: 396.26.0
2019-05-18 04:41:05.966032: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:198] kernel reported version is: 396.26.0
2019-05-18 04:41:05.966046: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:305] kernel version seems to match DSO: 396.26.0
Epoch 1/25
 - 8807s - loss: 213.8062 - mean_squared_error: 356.3437 - val_loss: 153.0065 - val_mean_squared_error: 255.0108
Epoch 2/25
 - 9206s - loss: 164.8367 - mean_squared_error: 274.7278 - val_loss: 131.0220 - val_mean_squared_error: 218.3701
Epoch 3/25
 - 8721s - loss: 157.5518 - mean_squared_error: 262.5863 - val_loss: 152.5665 - val_mean_squared_error: 254.2774
Epoch 4/25
 - 8383s - loss: 154.2287 - mean_squared_error: 257.0479 - val_loss: 155.2549 - val_mean_squared_error: 258.7582
Epoch 5/25
 - 8930s - loss: 151.8010 - mean_squared_error: 253.0017 - val_loss: 165.3128 - val_mean_squared_error: 275.5212
Epoch 6/25
 - 10517s - loss: 149.8901 - mean_squared_error: 249.8168 - val_loss: 133.1629 - val_mean_squared_error: 221.9381
Epoch 7/25
 - 11346s - loss: 148.8808 - mean_squared_error: 248.1346 - val_loss: 141.1980 - val_mean_squared_error: 235.3300
Epoch 8/25
 - 10917s - loss: 147.9293 - mean_squared_error: 246.5489 - val_loss: 130.9517 - val_mean_squared_error: 218.2528
Epoch 9/25
 - 9917s - loss: 147.3615 - mean_squared_error: 245.6025 - val_loss: 131.8232 - val_mean_squared_error: 219.7053
Epoch 10/25
 - 8822s - loss: 146.6416 - mean_squared_error: 244.4026 - val_loss: 130.7135 - val_mean_squared_error: 217.8558
Epoch 11/25
 - 10505s - loss: 146.1362 - mean_squared_error: 243.5604 - val_loss: 123.0504 - val_mean_squared_error: 205.0840
Epoch 12/25
 - 12242s - loss: 145.3682 - mean_squared_error: 242.2804 - val_loss: 142.4908 - val_mean_squared_error: 237.4847
Epoch 13/25
 - 10700s - loss: 144.7273 - mean_squared_error: 241.2122 - val_loss: 134.8651 - val_mean_squared_error: 224.7751
Epoch 14/25
 - 10286s - loss: 144.1081 - mean_squared_error: 240.1802 - val_loss: 130.3000 - val_mean_squared_error: 217.1666
Epoch 15/25
 - 10356s - loss: 143.5507 - mean_squared_error: 239.2512 - val_loss: 150.7142 - val_mean_squared_error: 251.1904
Epoch 16/25
 - 10598s - loss: 143.0866 - mean_squared_error: 238.4776 - val_loss: 178.7056 - val_mean_squared_error: 297.8427
Epoch 17/25
 - 8187s - loss: 142.6316 - mean_squared_error: 237.7193 - val_loss: 173.6978 - val_mean_squared_error: 289.4963
Epoch 18/25
 - 7132s - loss: 142.1515 - mean_squared_error: 236.9191 - val_loss: 160.9403 - val_mean_squared_error: 268.2338
Epoch 19/25
 - 6944s - loss: 141.8127 - mean_squared_error: 236.3544 - val_loss: 166.8863 - val_mean_squared_error: 278.1439
Epoch 20/25
 - 7591s - loss: 141.3108 - mean_squared_error: 235.5180 - val_loss: 160.8521 - val_mean_squared_error: 268.0868
Epoch 21/25
 - 6857s - loss: 140.9415 - mean_squared_error: 234.9025 - val_loss: 172.1263 - val_mean_squared_error: 286.8771
/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Done with trial 4
