2019-05-18 17:08:07.639865: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-18 17:08:08.046411: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties: 
name: TITAN V major: 7 minor: 0 memoryClockRate(GHz): 1.455
pciBusID: 0000:82:00.0
totalMemory: 11.75GiB freeMemory: 9.78GiB
2019-05-18 17:08:08.046495: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2019-05-18 17:08:08.765628: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-05-18 17:08:08.765703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0 
2019-05-18 17:08:08.765717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N 
2019-05-18 17:08:08.766130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 9429 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:82:00.0, compute capability: 7.0)
Epoch 1/25
 - 1660s - loss: 332.8575 - mean_squared_error: 332.8575 - val_loss: 222.5909 - val_mean_squared_error: 222.5909
Epoch 2/25
 - 1073s - loss: 253.9187 - mean_squared_error: 253.9187 - val_loss: 260.9202 - val_mean_squared_error: 260.9202
Epoch 3/25
 - 1074s - loss: 242.0385 - mean_squared_error: 242.0385 - val_loss: 221.9539 - val_mean_squared_error: 221.9539
Epoch 4/25
 - 1019s - loss: 236.2078 - mean_squared_error: 236.2078 - val_loss: 204.0066 - val_mean_squared_error: 204.0066
Epoch 5/25
 - 1817s - loss: 232.9983 - mean_squared_error: 232.9983 - val_loss: 193.9169 - val_mean_squared_error: 193.9169
Epoch 6/25
 - 1099s - loss: 230.6075 - mean_squared_error: 230.6075 - val_loss: 218.3386 - val_mean_squared_error: 218.3386
Epoch 7/25
 - 1585s - loss: 228.8289 - mean_squared_error: 228.8289 - val_loss: 202.6913 - val_mean_squared_error: 202.6913
Epoch 8/25
 - 1374s - loss: 227.3742 - mean_squared_error: 227.3742 - val_loss: 187.8566 - val_mean_squared_error: 187.8566
Epoch 9/25
 - 1028s - loss: 225.9400 - mean_squared_error: 225.9400 - val_loss: 201.3035 - val_mean_squared_error: 201.3035
Epoch 10/25
 - 1011s - loss: 224.4360 - mean_squared_error: 224.4360 - val_loss: 210.9672 - val_mean_squared_error: 210.9672
Epoch 11/25
 - 1028s - loss: 223.1162 - mean_squared_error: 223.1162 - val_loss: 234.5944 - val_mean_squared_error: 234.5944
Epoch 12/25
 - 869s - loss: 221.9536 - mean_squared_error: 221.9536 - val_loss: 193.4604 - val_mean_squared_error: 193.4604
Epoch 13/25
 - 913s - loss: 221.3048 - mean_squared_error: 221.3048 - val_loss: 234.7452 - val_mean_squared_error: 234.7452
Epoch 14/25
 - 888s - loss: 220.4620 - mean_squared_error: 220.4620 - val_loss: 203.8321 - val_mean_squared_error: 203.8321
Epoch 15/25
 - 819s - loss: 219.7220 - mean_squared_error: 219.7220 - val_loss: 233.8642 - val_mean_squared_error: 233.8642
Epoch 16/25
 - 2515s - loss: 218.9762 - mean_squared_error: 218.9762 - val_loss: 207.5752 - val_mean_squared_error: 207.5752
Epoch 17/25
 - 784s - loss: 218.4603 - mean_squared_error: 218.4603 - val_loss: 221.8519 - val_mean_squared_error: 221.8519
Epoch 18/25
 - 818s - loss: 217.8054 - mean_squared_error: 217.8054 - val_loss: 210.4649 - val_mean_squared_error: 210.4649
/pkg/python/3.6.1-centos7/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Done with trial 28
